# Generated by Django 6.0 on 2025-12-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0004_projectbatch_status_and_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
