# Generated by Django 6.0 on 2026-01-13 09:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_workflow_node_roles(apps, schema_editor):
    """迁移工作流节点的角色数据"""
    WorkflowNode = apps.get_model("system_settings", "WorkflowNode")
    Role = apps.get_model("users", "Role")

    # 获取所有角色对象
    roles_dict = {role.code: role for role in Role.objects.all()}

    # 更新所有工作流节点
    for node in WorkflowNode.objects.all():
        if node.role and node.role in roles_dict:
            node.role_fk = roles_dict[node.role]
            node.save(update_fields=["role_fk"])


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0008_workflow_review_templates"),
        ("users", "0005_add_role_permission_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflownode",
            name="role_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_nodes",
                to="users.role",
                verbose_name="执行角色",
            ),
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEACHER", "导师"),
                    ("LEVEL2_ADMIN", "二级管理员"),
                    ("LEVEL1_ADMIN", "一级管理员"),
                    ("EXPERT", "专家"),
                ],
                max_length=20,
                verbose_name="角色（旧）",
            ),
        ),
        # 迁移现有工作流节点的角色数据
        migrations.RunPython(migrate_workflow_node_roles, migrations.RunPython.noop),
    ]
