# Generated by Django 6.0 on 2026-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0009_add_workflow_node_role_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='allowed_reject_to',
            field=models.JSONField(blank=True, default=list, help_text='存储可以退回到的节点ID数组', verbose_name='允许退回的节点ID列表'),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('SUBMIT', '提交'), ('REVIEW', '审核'), ('EXPERT_REVIEW', '专家评审'), ('APPROVAL', '管理员确认')], max_length=20, verbose_name='节点类型'),
        ),
    ]
