# Generated by Django 6.0 on 2026-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0010_workflownode_allowed_reject_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='end_date',
            field=models.DateField(blank=True, help_text='该节点必须完成的日期', null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='start_date',
            field=models.DateField(blank=True, help_text='该节点可以开始执行的日期', null=True, verbose_name='开始日期'),
        ),
    ]
