# Generated by Django 6.0 on 2026-01-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_review_review_template_and_more'),
        ('system_settings', '0011_workflownode_end_date_workflownode_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflownode',
            name='review_template',
        ),
        migrations.RemoveField(
            model_name='reviewtemplateitem',
            name='template',
        ),
        migrations.DeleteModel(
            name='ReviewTemplate',
        ),
        migrations.DeleteModel(
            name='ReviewTemplateItem',
        ),
    ]
