# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0012_remove_workflownode_review_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='require_expert_review',
            field=models.BooleanField(
                default=False,
                help_text='管理员节点开启后需先完成专家评审才能终审',
                verbose_name='是否需要专家评审',
            ),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(
                choices=[
                    ('SUBMIT', '提交'),
                    ('REVIEW', '审核'),
                    ('APPROVAL', '管理员确认'),
                ],
                max_length=20,
                verbose_name='节点类型',
            ),
        ),
    ]
