# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0013_workflownode_require_expert_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseScopeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('APPLICATION', '立项'), ('MID_TERM', '中期'), ('CLOSURE', '结题')], max_length=20, verbose_name='流程阶段')),
                ('scope_type', models.CharField(choices=[('COLLEGE', '学院'), ('PROJECT_CATEGORY', '项目类别'), ('PROJECT_LEVEL', '项目级别'), ('KEY_FIELD', '重点领域')], max_length=50, verbose_name='数据范围维度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_scopes', to='system_settings.projectbatch', verbose_name='所属批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_phase_scopes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_phase_scopes', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '阶段数据范围配置',
                'verbose_name_plural': '阶段数据范围配置',
                'db_table': 'phase_scope_configs',
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='AdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('APPLICATION', '立项'), ('MID_TERM', '中期'), ('CLOSURE', '结题')], max_length=20, verbose_name='流程阶段')),
                ('scope_value', models.CharField(max_length=100, verbose_name='维度值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to=settings.AUTH_USER_MODEL, verbose_name='管理员用户')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='system_settings.projectbatch', verbose_name='所属批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_assignments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_admin_assignments', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('workflow_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='system_settings.workflownode', verbose_name='工作流节点')),
            ],
            options={
                'verbose_name': '管理员分配',
                'verbose_name_plural': '管理员分配',
                'db_table': 'admin_assignments',
                'ordering': ['-created_at'],
                'unique_together': {('batch', 'phase', 'workflow_node', 'scope_value')},
            },
        ),
        migrations.AddConstraint(
            model_name='adminassignment',
            constraint=models.UniqueConstraint(fields=('batch', 'phase', 'scope_value', 'admin_user'), name='uniq_admin_assignment_user'),
        ),
    ]
