# Generated by Django 6.0 on 2026-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0014_phase_scope_and_admin_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='role',
            field=models.CharField(blank=True, choices=[('TEACHER', '导师'), ('LEVEL2_ADMIN', '二级管理员'), ('LEVEL1_ADMIN', '一级管理员')], max_length=20, verbose_name='角色（旧）'),
        ),
    ]
