# Generated by Django 6.0 on 2026-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0015_alter_workflownode_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhaseScopeConfig",
        ),
    ]
