# Generated by Django 6.0 on 2026-01-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0016_delete_phase_scope_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflownode',
            name='scope',
        ),
    ]
