# Generated by Django 6.0 on 2026-01-14 15:58

from django.db import migrations, models


def convert_array_to_single(apps, schema_editor):
    """将allowed_reject_to从JSONB数组转换为单个整数"""
    # 使用原生SQL来转换数据
    with schema_editor.connection.cursor() as cursor:
        # 首先添加临时列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            ADD COLUMN allowed_reject_to_temp INTEGER;
        """)

        # 将数组的第一个元素提取到临时列
        cursor.execute("""
            UPDATE workflow_nodes 
            SET allowed_reject_to_temp = CAST(allowed_reject_to->>0 AS INTEGER)
            WHERE allowed_reject_to IS NOT NULL 
            AND jsonb_array_length(allowed_reject_to) > 0;
        """)

        # 删除原列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            DROP COLUMN allowed_reject_to;
        """)

        # 重命名临时列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            RENAME COLUMN allowed_reject_to_temp TO allowed_reject_to;
        """)


def reverse_convert(apps, schema_editor):
    """反向迁移：将整数转换回数组"""
    with schema_editor.connection.cursor() as cursor:
        # 添加临时列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            ADD COLUMN allowed_reject_to_temp JSONB;
        """)

        # 将整数转换为单元素数组
        cursor.execute("""
            UPDATE workflow_nodes 
            SET allowed_reject_to_temp = jsonb_build_array(allowed_reject_to)
            WHERE allowed_reject_to IS NOT NULL;
        """)

        # 对于NULL值，设置为空数组
        cursor.execute("""
            UPDATE workflow_nodes 
            SET allowed_reject_to_temp = '[]'::jsonb
            WHERE allowed_reject_to IS NULL;
        """)

        # 删除原列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            DROP COLUMN allowed_reject_to;
        """)

        # 重命名临时列
        cursor.execute("""
            ALTER TABLE workflow_nodes 
            RENAME COLUMN allowed_reject_to_temp TO allowed_reject_to;
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("system_settings", "0017_remove_workflownode_scope"),
    ]

    operations = [
        migrations.RunPython(convert_array_to_single, reverse_convert),
        migrations.AlterField(
            model_name="workflownode",
            name="allowed_reject_to",
            field=models.IntegerField(
                blank=True,
                help_text="存储可以退回到的节点ID",
                null=True,
                verbose_name="允许退回的节点ID",
            ),
        ),
    ]
