# Generated by Codex on 2026-01-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0020_remove_workflownode_date_window"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflownode",
            name="role",
        ),
        migrations.RemoveField(
            model_name="workflownode",
            name="review_level",
        ),
    ]
