# Generated by Codex on 2026-01-18

from django.db import migrations


def set_submit_role_fk(apps, schema_editor):
    WorkflowNode = apps.get_model("system_settings", "WorkflowNode")
    Role = apps.get_model("users", "Role")

    roles = {
        role.code: role
        for role in Role.objects.filter(
            code__in=["STUDENT", "TEACHER", "LEVEL2_ADMIN", "LEVEL1_ADMIN"]
        )
    }
    student_role = roles.get("STUDENT")
    if not student_role:
        return

    role_by_keyword = [
        ("TEACHER", roles.get("TEACHER")),
        ("LEVEL2", roles.get("LEVEL2_ADMIN")),
        ("COLLEGE", roles.get("LEVEL2_ADMIN")),
        ("LEVEL1", roles.get("LEVEL1_ADMIN")),
        ("SCHOOL", roles.get("LEVEL1_ADMIN")),
    ]

    for node in WorkflowNode.objects.filter(role_fk__isnull=True):
        role = None
        if node.node_type == "SUBMIT":
            role = student_role
        else:
            code_upper = (node.code or "").upper()
            name_text = node.name or ""
            for keyword, candidate in role_by_keyword:
                if candidate and keyword in code_upper:
                    role = candidate
                    break
            if not role:
                if roles.get("TEACHER") and "导师" in name_text:
                    role = roles.get("TEACHER")
                elif roles.get("LEVEL2_ADMIN") and "学院" in name_text:
                    role = roles.get("LEVEL2_ADMIN")
                elif roles.get("LEVEL1_ADMIN") and (
                    "校级" in name_text or "学校" in name_text
                ):
                    role = roles.get("LEVEL1_ADMIN")
        if role:
            node.role_fk = role
            node.save(update_fields=["role_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("system_settings", "0021_remove_workflownode_role_review_level"),
        ("users", "0018_alter_user_expert_scope"),
    ]

    operations = [
        migrations.RunPython(set_submit_role_fk, migrations.RunPython.noop),
    ]
