# Generated by Django 6.0 on 2025-12-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='项目年份'),
        ),
    ]
