# Generated by Django 6.0 on 2025-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_domain_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='重点领域代码'),
        ),
    ]
