# Generated by Django 6.0 on 2025-12-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_seed_project_level_items'),
        ('projects', '0005_project_mid_term_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='支出事项')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('expenditure_date', models.DateField(verbose_name='支出日期')),
                ('proof_file', models.FileField(blank=True, max_length=255, null=True, upload_to='expenditures/', verbose_name='凭证文件')),
                ('status', models.CharField(choices=[('RECORDED', '已录入')], default='RECORDED', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_expenditures', to='dictionaries.dictionaryitem', verbose_name='支出类别')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '经费支出',
                'verbose_name_plural': '经费支出',
                'db_table': 'project_expenditures',
                'ordering': ['-expenditure_date', '-created_at'],
                'indexes': [models.Index(fields=['project', 'expenditure_date'], name='project_exp_project_fcb7bd_idx')],
            },
        ),
    ]
