# Generated by Django 6.0 on 2025-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectexpenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('TEACHER_AUDITING', '导师审核中'), ('TEACHER_APPROVED', '导师审核通过'), ('TEACHER_REJECTED', '导师审核不通过'), ('COLLEGE_AUDITING', '学院审核中'), ('IN_PROGRESS', '进行中'), ('MID_TERM_DRAFT', '中期草稿'), ('MID_TERM_SUBMITTED', '中期已提交'), ('MID_TERM_REVIEWING', '中期审核中'), ('MID_TERM_APPROVED', '中期审核通过'), ('MID_TERM_REJECTED', '中期审核不通过'), ('CLOSURE_DRAFT', '结题草稿'), ('CLOSURE_SUBMITTED', '结题已提交'), ('CLOSURE_LEVEL2_REVIEWING', '结题二级审核中'), ('CLOSURE_LEVEL2_APPROVED', '结题二级审核通过'), ('CLOSURE_LEVEL2_REJECTED', '结题二级审核不通过'), ('CLOSURE_LEVEL1_REVIEWING', '结题一级审核中'), ('CLOSURE_LEVEL1_APPROVED', '结题一级审核通过'), ('CLOSURE_LEVEL1_REJECTED', '结题一级审核不通过'), ('COMPLETED', '已完成'), ('CLOSED', '已结题')], default='DRAFT', max_length=30, verbose_name='项目状态'),
        ),
    ]
