# Generated by Django 6.0 on 2025-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approved_budget",
            field=models.DecimalField(
                blank=True,
                null=True,
                max_digits=10,
                decimal_places=2,
                verbose_name="批准经费",
            ),
        ),
    ]
