# Generated by Codex on 2025-12-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_project_status_ready_for_closure"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="achievement_summary",
            field=models.TextField(blank=True, default="", verbose_name="结题成果简介"),
        ),
    ]
