# Generated by Django 6.0 on 2026-01-13 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_seed_project_level_items'),
        ('projects', '0020_project_discipline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原预算金额')),
                ('new_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新预算金额')),
                ('reason', models.TextField(verbose_name='变更原因')),
                ('budget_breakdown', models.JSONField(blank=True, default=dict, verbose_name='预算明细')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审核'), ('TEACHER_APPROVED', '导师审核通过'), ('TEACHER_REJECTED', '导师审核不通过'), ('LEVEL2_APPROVED', '学院审核通过'), ('LEVEL2_REJECTED', '学院审核不通过'), ('LEVEL1_APPROVED', '校级审核通过'), ('LEVEL1_REJECTED', '校级审核不通过'), ('APPROVED', '审核通过'), ('REJECTED', '审核不通过')], default='DRAFT', max_length=30, verbose_name='状态')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='导师意见')),
                ('teacher_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='导师审核时间')),
                ('level2_comment', models.TextField(blank=True, verbose_name='学院意见')),
                ('level2_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='学院审核时间')),
                ('level1_comment', models.TextField(blank=True, verbose_name='校级意见')),
                ('level1_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='校级审核时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预算变更申请',
                'verbose_name_plural': '预算变更申请',
                'db_table': 'budget_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectarchive',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='归档元数据'),
        ),
        migrations.AddField(
            model_name='projectexpenditure',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='projectexpenditure',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='projectexpenditure',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='projectexpenditure',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expenditures', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='projectexpenditure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('TEACHER_AUDITING', '导师审核中'), ('TEACHER_APPROVED', '导师审核通过'), ('TEACHER_REJECTED', '导师审核不通过'), ('COLLEGE_AUDITING', '学院审核中'), ('LEVEL1_AUDITING', '校级审核中'), ('APPLICATION_RETURNED', '立项退回修改'), ('IN_PROGRESS', '进行中'), ('TASK_BOOK_DRAFT', '任务书草稿'), ('TASK_BOOK_SUBMITTED', '任务书已提交'), ('TASK_BOOK_REVIEWING', '任务书审核中'), ('TASK_BOOK_APPROVED', '任务书审核通过'), ('TASK_BOOK_REJECTED', '任务书审核不通过'), ('TASK_BOOK_RETURNED', '任务书退回修改'), ('MID_TERM_DRAFT', '中期草稿'), ('MID_TERM_SUBMITTED', '中期已提交'), ('MID_TERM_REVIEWING', '中期审核中'), ('MID_TERM_APPROVED', '中期审核通过'), ('READY_FOR_CLOSURE', '待结题'), ('MID_TERM_REJECTED', '中期审核不通过'), ('MID_TERM_RETURNED', '中期退回修改'), ('CLOSURE_DRAFT', '结题草稿'), ('CLOSURE_SUBMITTED', '结题已提交'), ('CLOSURE_LEVEL2_REVIEWING', '结题二级审核中'), ('CLOSURE_LEVEL2_APPROVED', '结题二级审核通过'), ('CLOSURE_LEVEL2_REJECTED', '结题二级审核不通过'), ('CLOSURE_LEVEL1_REVIEWING', '结题一级审核中'), ('CLOSURE_LEVEL1_APPROVED', '结题一级审核通过'), ('CLOSURE_LEVEL1_REJECTED', '结题一级审核不通过'), ('CLOSURE_RETURNED', '结题退回修改'), ('COMPLETED', '已完成'), ('CLOSED', '已结题'), ('TERMINATED', '已终止')], default='DRAFT', max_length=30, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectexpenditure',
            name='status',
            field=models.CharField(choices=[('RECORDED', '已录入'), ('PENDING', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '审核不通过')], default='RECORDED', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='projectphaseinstance',
            name='phase',
            field=models.CharField(choices=[('APPLICATION', '立项'), ('TASK_BOOK', '任务书'), ('MID_TERM', '中期'), ('CLOSURE', '结题')], max_length=20, verbose_name='阶段'),
        ),
        migrations.AddIndex(
            model_name='projectarchive',
            index=models.Index(fields=['-archived_at'], name='project_arc_archive_aee040_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenditure',
            index=models.Index(fields=['status'], name='project_exp_status_86c717_idx'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budget_changes', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='level1_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_level1_reviews', to=settings.AUTH_USER_MODEL, verbose_name='校级审核人'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='level2_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_level2_reviews', to=settings.AUTH_USER_MODEL, verbose_name='学院审核人'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_change_requests', to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='budgetchangerequest',
            name='teacher_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_teacher_reviews', to=settings.AUTH_USER_MODEL, verbose_name='导师审核人'),
        ),
        migrations.AddIndex(
            model_name='budgetchangerequest',
            index=models.Index(fields=['project', 'status'], name='budget_chan_project_e9ed22_idx'),
        ),
    ]
