# Generated by Django 6.0 on 2026-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_budgetchangerequest_projectarchive_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphaseinstance',
            name='current_node_id',
            field=models.IntegerField(blank=True, help_text='关联到 WorkflowNode.id，用于动态工作流引擎', null=True, verbose_name='当前流程节点ID'),
        ),
    ]
