# Generated by Django 6.0 on 2026-01-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_delete_project_push_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecyclebin',
            name='resource_type',
            field=models.CharField(choices=[('APPLICATION', '立项申报'), ('MID_TERM', '中期提交'), ('CLOSURE', '结题提交'), ('ACHIEVEMENT', '成果'), ('EXPENDITURE', '经费支出')], max_length=20, verbose_name='资源类型'),
        ),
    ]
