# Generated by Codex on 2026-01-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_migrate_mid_term_approved_status"),
        ("system_settings", "0021_remove_workflownode_role_review_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectchangereview",
            name="workflow_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_reviews",
                to="system_settings.workflownode",
                verbose_name="关联工作流节点",
            ),
        ),
        migrations.RemoveField(
            model_name="projectchangereview",
            name="review_level",
        ),
    ]
