# Generated by Codex on 2025-02-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0033_expenditure_workflow"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="achievement_summary"),
        migrations.RemoveField(model_name="project", name="category_description"),
        migrations.RemoveField(model_name="project", name="innovation_points"),
        migrations.RemoveField(model_name="project", name="ranking"),
        migrations.RemoveField(model_name="project", name="research_content"),
        migrations.RemoveField(model_name="project", name="research_plan"),
        migrations.RemoveField(model_name="project", name="self_funding"),
    ]
