# Generated by Codex on 2025-02-16

from django.db import migrations


def purge_legacy_change_requests(apps, schema_editor):
    ProjectChangeRequest = apps.get_model("projects", "ProjectChangeRequest")
    ProjectChangeRequest.objects.filter(
        request_type__in=["EXTENSION", "TERMINATION"]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0034_remove_project_unused_fields"),
    ]

    operations = [
        migrations.RunPython(purge_legacy_change_requests, migrations.RunPython.noop),
        migrations.RemoveField(model_name="projectchangerequest", name="requested_end_date"),
    ]
