--
-- PostgreSQL database dump
--

\restrict 5g9r8DaLlg8JpXHZKnSbcfPi92T7OvX0dhVr7lMHNAkP4rzKq6eKMuNvXtPpRRt

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificate_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.certificate_settings (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    school_name character varying(100) NOT NULL,
    issuer_name character varying(100) NOT NULL,
    template_code character varying(50) NOT NULL,
    background_image character varying(100),
    seal_image character varying(100),
    style_config jsonb NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_category_id bigint,
    project_level_id bigint,
    updated_by_id bigint
);


ALTER TABLE public.certificate_settings OWNER TO postgres;

--
-- Name: certificate_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.certificate_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificate_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dictionary_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dictionary_items (
    id bigint NOT NULL,
    value character varying(50) NOT NULL,
    label character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    extra_data jsonb,
    description character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dict_type_id bigint NOT NULL,
    template_file character varying(100)
);


ALTER TABLE public.dictionary_items OWNER TO postgres;

--
-- Name: dictionary_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dictionary_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictionary_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dictionary_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dictionary_types (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    is_system boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.dictionary_types OWNER TO postgres;

--
-- Name: dictionary_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dictionary_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dictionary_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: expert_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expert_groups (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    scope character varying(20) NOT NULL
);


ALTER TABLE public.expert_groups OWNER TO postgres;

--
-- Name: expert_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expert_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expert_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expert_groups_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expert_groups_members (
    id bigint NOT NULL,
    expertgroup_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.expert_groups_members OWNER TO postgres;

--
-- Name: expert_groups_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expert_groups_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expert_groups_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    notification_type character varying(20) NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    recipient_id bigint NOT NULL,
    related_project_id bigint
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_achievements (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    authors character varying(200) NOT NULL,
    journal character varying(200) NOT NULL,
    publication_date date,
    doi character varying(100) NOT NULL,
    patent_no character varying(100) NOT NULL,
    patent_type character varying(50) NOT NULL,
    applicant character varying(200) NOT NULL,
    copyright_no character varying(100) NOT NULL,
    copyright_owner character varying(200) NOT NULL,
    competition_name character varying(200) NOT NULL,
    award_level character varying(50) NOT NULL,
    award_date date,
    attachment character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    achievement_type_id bigint NOT NULL,
    project_id bigint NOT NULL,
    extra_data jsonb NOT NULL
);


ALTER TABLE public.project_achievements OWNER TO postgres;

--
-- Name: project_achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_advisors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_advisors (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.project_advisors OWNER TO postgres;

--
-- Name: project_advisors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_advisors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_advisors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_archives; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_archives (
    id bigint NOT NULL,
    snapshot jsonb NOT NULL,
    attachments jsonb NOT NULL,
    archived_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    metadata jsonb NOT NULL
);


ALTER TABLE public.project_archives OWNER TO postgres;

--
-- Name: project_archives_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_archives ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_archives_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_batches; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_batches (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    year integer NOT NULL,
    code character varying(50) NOT NULL,
    is_current boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    is_deleted boolean NOT NULL
);


ALTER TABLE public.project_batches OWNER TO postgres;

--
-- Name: project_batches_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_change_requests; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_change_requests (
    id bigint NOT NULL,
    request_type character varying(20) NOT NULL,
    reason text NOT NULL,
    change_data jsonb,
    attachment character varying(255),
    status character varying(30) NOT NULL,
    submitted_at timestamp with time zone,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.project_change_requests OWNER TO postgres;

--
-- Name: project_change_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_change_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_change_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_change_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_change_reviews (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    comments text NOT NULL,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    change_request_id bigint NOT NULL,
    reviewer_id bigint,
    workflow_node_id bigint
);


ALTER TABLE public.project_change_reviews OWNER TO postgres;

--
-- Name: project_change_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_change_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_change_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_expenditure_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_expenditure_reviews (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    comments text NOT NULL,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    expenditure_id bigint NOT NULL,
    reviewer_id bigint,
    workflow_node_id bigint
);


ALTER TABLE public.project_expenditure_reviews OWNER TO postgres;

--
-- Name: project_expenditure_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_expenditure_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_expenditure_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_expenditures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_expenditures (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    amount numeric(10,2) NOT NULL,
    expenditure_date date NOT NULL,
    proof_file character varying(255),
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint NOT NULL,
    project_id bigint NOT NULL,
    is_deleted boolean NOT NULL,
    review_comment text NOT NULL,
    reviewed_at timestamp with time zone,
    reviewed_by_id bigint,
    updated_at timestamp with time zone NOT NULL,
    leader_review_status character varying(20) NOT NULL,
    leader_reviewed_at timestamp with time zone,
    leader_review_comment text NOT NULL,
    leader_reviewed_by_id bigint,
    current_node_id integer
);


ALTER TABLE public.project_expenditures OWNER TO postgres;

--
-- Name: project_expenditures_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_expenditures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_expenditures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_members (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    join_date date NOT NULL,
    contribution text NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.project_members OWNER TO postgres;

--
-- Name: project_members_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_phase_instances; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.project_phase_instances (
    id bigint NOT NULL,
    phase character varying(20) NOT NULL,
    attempt_no integer NOT NULL,
    step character varying(50) NOT NULL,
    state character varying(20) NOT NULL,
    return_to character varying(20) NOT NULL,
    returned_reason text NOT NULL,
    returned_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    project_id bigint NOT NULL,
    current_node_id integer,
    CONSTRAINT project_phase_instances_attempt_no_check CHECK ((attempt_no >= 0))
);


ALTER TABLE public.project_phase_instances OWNER TO postgres;

--
-- Name: project_phase_instances_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.project_phase_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_phase_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    project_no character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    is_key_field boolean NOT NULL,
    start_date date,
    end_date date,
    budget numeric(10,2) NOT NULL,
    expected_results text NOT NULL,
    proposal_file character varying(255),
    attachment_file character varying(255),
    final_report character varying(255),
    achievement_file character varying(255),
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    submitted_at timestamp with time zone,
    closure_applied_at timestamp with time zone,
    category_id bigint,
    leader_id bigint NOT NULL,
    level_id bigint,
    source_id bigint,
    year integer NOT NULL,
    key_domain_code character varying(50) NOT NULL,
    mid_term_report character varying(255),
    mid_term_submitted_at timestamp with time zone,
    approved_budget numeric(10,2),
    batch_id bigint,
    expected_results_data jsonb NOT NULL
);


ALTER TABLE public.projects OWNER TO postgres;

--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    review_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    comments text NOT NULL,
    score integer,
    closure_rating character varying(20),
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    project_id bigint NOT NULL,
    reviewer_id bigint,
    phase_instance_id bigint,
    score_details jsonb NOT NULL,
    workflow_node_id bigint,
    is_expert_review boolean NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    is_system boolean NOT NULL,
    is_active boolean NOT NULL,
    default_route character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    scope_dimension character varying(50)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_settings (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    data jsonb NOT NULL,
    is_locked boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    updated_by_id bigint,
    batch_id bigint
);


ALTER TABLE public.system_settings OWNER TO postgres;

--
-- Name: system_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    employee_id character varying(20) NOT NULL,
    real_name character varying(50) NOT NULL,
    phone character varying(11) NOT NULL,
    email character varying(254) NOT NULL,
    major character varying(100) NOT NULL,
    grade character varying(10) NOT NULL,
    class_name character varying(50) NOT NULL,
    college character varying(100) NOT NULL,
    department character varying(100) NOT NULL,
    avatar character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title character varying(50) NOT NULL,
    expert_scope character varying(20) NOT NULL,
    role_fk_id bigint,
    managed_scope_value_id bigint,
    gender character varying(10) NOT NULL,
    is_expert boolean NOT NULL,
    expert_assigned_by_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_configs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workflow_configs (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    phase character varying(20) NOT NULL,
    version integer NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    is_locked boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    batch_id bigint,
    created_by_id bigint,
    updated_by_id bigint
);


ALTER TABLE public.workflow_configs OWNER TO postgres;

--
-- Name: workflow_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workflow_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_nodes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workflow_nodes (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    node_type character varying(20) NOT NULL,
    return_policy character varying(20) NOT NULL,
    notice text NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    workflow_id bigint NOT NULL,
    role_fk_id bigint,
    require_expert_review boolean NOT NULL,
    allowed_reject_to integer
);


ALTER TABLE public.workflow_nodes OWNER TO postgres;

--
-- Name: workflow_nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workflow_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: certificate_settings certificate_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate_settings
    ADD CONSTRAINT certificate_settings_pkey PRIMARY KEY (id);


--
-- Name: dictionary_items dictionary_items_dict_type_id_value_d443096c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary_items
    ADD CONSTRAINT dictionary_items_dict_type_id_value_d443096c_uniq UNIQUE (dict_type_id, value);


--
-- Name: dictionary_items dictionary_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary_items
    ADD CONSTRAINT dictionary_items_pkey PRIMARY KEY (id);


--
-- Name: dictionary_types dictionary_types_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary_types
    ADD CONSTRAINT dictionary_types_code_key UNIQUE (code);


--
-- Name: dictionary_types dictionary_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary_types
    ADD CONSTRAINT dictionary_types_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: expert_groups_members expert_groups_members_expertgroup_id_user_id_abc88dfa_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups_members
    ADD CONSTRAINT expert_groups_members_expertgroup_id_user_id_abc88dfa_uniq UNIQUE (expertgroup_id, user_id);


--
-- Name: expert_groups_members expert_groups_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups_members
    ADD CONSTRAINT expert_groups_members_pkey PRIMARY KEY (id);


--
-- Name: expert_groups expert_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups
    ADD CONSTRAINT expert_groups_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: project_achievements project_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_achievements
    ADD CONSTRAINT project_achievements_pkey PRIMARY KEY (id);


--
-- Name: project_advisors project_advisors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_advisors
    ADD CONSTRAINT project_advisors_pkey PRIMARY KEY (id);


--
-- Name: project_archives project_archives_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_archives
    ADD CONSTRAINT project_archives_pkey PRIMARY KEY (id);


--
-- Name: project_archives project_archives_project_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_archives
    ADD CONSTRAINT project_archives_project_id_key UNIQUE (project_id);


--
-- Name: project_batches project_batches_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_batches
    ADD CONSTRAINT project_batches_code_key UNIQUE (code);


--
-- Name: project_batches project_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_batches
    ADD CONSTRAINT project_batches_pkey PRIMARY KEY (id);


--
-- Name: project_change_requests project_change_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_requests
    ADD CONSTRAINT project_change_requests_pkey PRIMARY KEY (id);


--
-- Name: project_change_reviews project_change_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_reviews
    ADD CONSTRAINT project_change_reviews_pkey PRIMARY KEY (id);


--
-- Name: project_expenditure_reviews project_expenditure_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditure_reviews
    ADD CONSTRAINT project_expenditure_reviews_pkey PRIMARY KEY (id);


--
-- Name: project_expenditures project_expenditures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditures
    ADD CONSTRAINT project_expenditures_pkey PRIMARY KEY (id);


--
-- Name: project_members project_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_pkey PRIMARY KEY (id);


--
-- Name: project_members project_members_project_id_user_id_ab18bfcc_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_project_id_user_id_ab18bfcc_uniq UNIQUE (project_id, user_id);


--
-- Name: project_phase_instances project_phase_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_phase_instances
    ADD CONSTRAINT project_phase_instances_pkey PRIMARY KEY (id);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: projects projects_project_no_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_project_no_key UNIQUE (project_no);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: roles roles_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_code_key UNIQUE (code);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: system_settings system_settings_code_batch_id_9901544a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_code_batch_id_9901544a_uniq UNIQUE (code, batch_id);


--
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (id);


--
-- Name: project_phase_instances uniq_project_phase_attempt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_phase_instances
    ADD CONSTRAINT uniq_project_phase_attempt UNIQUE (project_id, phase, attempt_no);


--
-- Name: users users_employee_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_employee_id_key UNIQUE (employee_id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: workflow_configs workflow_configs_phase_batch_id_version_06d76f32_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_configs
    ADD CONSTRAINT workflow_configs_phase_batch_id_version_06d76f32_uniq UNIQUE (phase, batch_id, version);


--
-- Name: workflow_configs workflow_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_configs
    ADD CONSTRAINT workflow_configs_pkey PRIMARY KEY (id);


--
-- Name: workflow_nodes workflow_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_nodes
    ADD CONSTRAINT workflow_nodes_pkey PRIMARY KEY (id);


--
-- Name: workflow_nodes workflow_nodes_workflow_id_code_63ae61b1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_nodes
    ADD CONSTRAINT workflow_nodes_workflow_id_code_63ae61b1_uniq UNIQUE (workflow_id, code);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: certificate_settings_project_category_id_eb459b98; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX certificate_settings_project_category_id_eb459b98 ON public.certificate_settings USING btree (project_category_id);


--
-- Name: certificate_settings_project_level_id_0ca1dab1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX certificate_settings_project_level_id_0ca1dab1 ON public.certificate_settings USING btree (project_level_id);


--
-- Name: certificate_settings_updated_by_id_2d83e676; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX certificate_settings_updated_by_id_2d83e676 ON public.certificate_settings USING btree (updated_by_id);


--
-- Name: dictionary__dict_ty_efa91e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dictionary__dict_ty_efa91e_idx ON public.dictionary_items USING btree (dict_type_id, is_active);


--
-- Name: dictionary_items_dict_type_id_08d3c96f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dictionary_items_dict_type_id_08d3c96f ON public.dictionary_items USING btree (dict_type_id);


--
-- Name: dictionary_items_value_cc3d1c81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dictionary_items_value_cc3d1c81 ON public.dictionary_items USING btree (value);


--
-- Name: dictionary_items_value_cc3d1c81_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dictionary_items_value_cc3d1c81_like ON public.dictionary_items USING btree (value varchar_pattern_ops);


--
-- Name: dictionary_types_code_0d0f74a4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX dictionary_types_code_0d0f74a4_like ON public.dictionary_types USING btree (code varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: expert_groups_created_by_id_ea191c03; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX expert_groups_created_by_id_ea191c03 ON public.expert_groups USING btree (created_by_id);


--
-- Name: expert_groups_members_expertgroup_id_c0b06855; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX expert_groups_members_expertgroup_id_c0b06855 ON public.expert_groups_members USING btree (expertgroup_id);


--
-- Name: expert_groups_members_user_id_94d717a7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX expert_groups_members_user_id_94d717a7 ON public.expert_groups_members USING btree (user_id);


--
-- Name: notificatio_recipie_583549_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificatio_recipie_583549_idx ON public.notifications USING btree (recipient_id, is_read);


--
-- Name: notifications_recipient_id_e1133bac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_recipient_id_e1133bac ON public.notifications USING btree (recipient_id);


--
-- Name: notifications_related_project_id_937ebb75; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_related_project_id_937ebb75 ON public.notifications USING btree (related_project_id);


--
-- Name: project_ach_project_5cdff8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_ach_project_5cdff8_idx ON public.project_achievements USING btree (project_id, achievement_type_id);


--
-- Name: project_achievements_achievement_type_id_1d76d968; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_achievements_achievement_type_id_1d76d968 ON public.project_achievements USING btree (achievement_type_id);


--
-- Name: project_achievements_project_id_99c3182e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_achievements_project_id_99c3182e ON public.project_achievements USING btree (project_id);


--
-- Name: project_advisors_project_id_d2ef5924; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_advisors_project_id_d2ef5924 ON public.project_advisors USING btree (project_id);


--
-- Name: project_advisors_user_id_e397bc74; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_advisors_user_id_e397bc74 ON public.project_advisors USING btree (user_id);


--
-- Name: project_arc_archive_aee040_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_arc_archive_aee040_idx ON public.project_archives USING btree (archived_at DESC);


--
-- Name: project_batches_code_560841e3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_batches_code_560841e3_like ON public.project_batches USING btree (code varchar_pattern_ops);


--
-- Name: project_change_requests_created_by_id_58f7c62d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_change_requests_created_by_id_58f7c62d ON public.project_change_requests USING btree (created_by_id);


--
-- Name: project_change_requests_project_id_3231f0af; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_change_requests_project_id_3231f0af ON public.project_change_requests USING btree (project_id);


--
-- Name: project_change_reviews_change_request_id_7de00e2e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_change_reviews_change_request_id_7de00e2e ON public.project_change_reviews USING btree (change_request_id);


--
-- Name: project_change_reviews_reviewer_id_3abd4640; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_change_reviews_reviewer_id_3abd4640 ON public.project_change_reviews USING btree (reviewer_id);


--
-- Name: project_change_reviews_workflow_node_id_5aa47440; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_change_reviews_workflow_node_id_5aa47440 ON public.project_change_reviews USING btree (workflow_node_id);


--
-- Name: project_exp_project_fcb7bd_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_exp_project_fcb7bd_idx ON public.project_expenditures USING btree (project_id, expenditure_date);


--
-- Name: project_exp_status_86c717_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_exp_status_86c717_idx ON public.project_expenditures USING btree (status);


--
-- Name: project_expenditure_reviews_expenditure_id_d8259029; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditure_reviews_expenditure_id_d8259029 ON public.project_expenditure_reviews USING btree (expenditure_id);


--
-- Name: project_expenditure_reviews_reviewer_id_954d0e0c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditure_reviews_reviewer_id_954d0e0c ON public.project_expenditure_reviews USING btree (reviewer_id);


--
-- Name: project_expenditure_reviews_workflow_node_id_d352905a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditure_reviews_workflow_node_id_d352905a ON public.project_expenditure_reviews USING btree (workflow_node_id);


--
-- Name: project_expenditures_created_by_id_283ff779; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditures_created_by_id_283ff779 ON public.project_expenditures USING btree (created_by_id);


--
-- Name: project_expenditures_leader_reviewed_by_id_3359cdab; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditures_leader_reviewed_by_id_3359cdab ON public.project_expenditures USING btree (leader_reviewed_by_id);


--
-- Name: project_expenditures_project_id_6c79dd16; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditures_project_id_6c79dd16 ON public.project_expenditures USING btree (project_id);


--
-- Name: project_expenditures_reviewed_by_id_4a719410; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_expenditures_reviewed_by_id_4a719410 ON public.project_expenditures USING btree (reviewed_by_id);


--
-- Name: project_members_project_id_bf2e42ec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_members_project_id_bf2e42ec ON public.project_members USING btree (project_id);


--
-- Name: project_members_user_id_2e9d44b1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_members_user_id_2e9d44b1 ON public.project_members USING btree (user_id);


--
-- Name: project_phase_instances_created_by_id_7783b14c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_phase_instances_created_by_id_7783b14c ON public.project_phase_instances USING btree (created_by_id);


--
-- Name: project_phase_instances_project_id_9f3b1467; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX project_phase_instances_project_id_9f3b1467 ON public.project_phase_instances USING btree (project_id);


--
-- Name: projects_batch_id_67b3e4b1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_batch_id_67b3e4b1 ON public.projects USING btree (batch_id);


--
-- Name: projects_category_id_2110ba9e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_category_id_2110ba9e ON public.projects USING btree (category_id);


--
-- Name: projects_leader_id_aabb0912; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_leader_id_aabb0912 ON public.projects USING btree (leader_id);


--
-- Name: projects_level_id_8a6f1c0b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_level_id_8a6f1c0b ON public.projects USING btree (level_id);


--
-- Name: projects_project_b2c64d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_project_b2c64d_idx ON public.projects USING btree (project_no);


--
-- Name: projects_project_no_b1aacc70_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_project_no_b1aacc70_like ON public.projects USING btree (project_no varchar_pattern_ops);


--
-- Name: projects_source_id_4682911e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_source_id_4682911e ON public.projects USING btree (source_id);


--
-- Name: projects_status_6303d7_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX projects_status_6303d7_idx ON public.projects USING btree (status);


--
-- Name: reviews_phase_instance_id_76b853a5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_phase_instance_id_76b853a5 ON public.reviews USING btree (phase_instance_id);


--
-- Name: reviews_proj_wfnode_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_proj_wfnode_idx ON public.reviews USING btree (project_id, workflow_node_id);


--
-- Name: reviews_project_id_1ffdb6d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_project_id_1ffdb6d1 ON public.reviews USING btree (project_id);


--
-- Name: reviews_reviewer_id_dbb954a8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_reviewer_id_dbb954a8 ON public.reviews USING btree (reviewer_id);


--
-- Name: reviews_status_12ddaa_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_status_12ddaa_idx ON public.reviews USING btree (status);


--
-- Name: reviews_workflow_node_id_ac4266fc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX reviews_workflow_node_id_ac4266fc ON public.reviews USING btree (workflow_node_id);


--
-- Name: roles_code_e726c310_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_code_e726c310_like ON public.roles USING btree (code varchar_pattern_ops);


--
-- Name: system_settings_batch_id_09927f7b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX system_settings_batch_id_09927f7b ON public.system_settings USING btree (batch_id);


--
-- Name: system_settings_updated_by_id_cf1dfbba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX system_settings_updated_by_id_cf1dfbba ON public.system_settings USING btree (updated_by_id);


--
-- Name: users_employee_id_7c8e0276_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_employee_id_7c8e0276_like ON public.users USING btree (employee_id varchar_pattern_ops);


--
-- Name: users_expert_assigned_by_id_174c6b8c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_expert_assigned_by_id_174c6b8c ON public.users USING btree (expert_assigned_by_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_managed_scope_value_id_b94b760f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_managed_scope_value_id_b94b760f ON public.users USING btree (managed_scope_value_id);


--
-- Name: users_role_fk_id_59b0f6c3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_role_fk_id_59b0f6c3 ON public.users USING btree (role_fk_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: workflow_configs_batch_id_537df69a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_configs_batch_id_537df69a ON public.workflow_configs USING btree (batch_id);


--
-- Name: workflow_configs_created_by_id_9ce1a151; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_configs_created_by_id_9ce1a151 ON public.workflow_configs USING btree (created_by_id);


--
-- Name: workflow_configs_updated_by_id_92af6584; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_configs_updated_by_id_92af6584 ON public.workflow_configs USING btree (updated_by_id);


--
-- Name: workflow_nodes_role_fk_id_505d424b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_nodes_role_fk_id_505d424b ON public.workflow_nodes USING btree (role_fk_id);


--
-- Name: workflow_nodes_workflow_id_411643ef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_nodes_workflow_id_411643ef ON public.workflow_nodes USING btree (workflow_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: certificate_settings certificate_settings_project_category_id_eb459b98_fk_dictionar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate_settings
    ADD CONSTRAINT certificate_settings_project_category_id_eb459b98_fk_dictionar FOREIGN KEY (project_category_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: certificate_settings certificate_settings_project_level_id_0ca1dab1_fk_dictionar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate_settings
    ADD CONSTRAINT certificate_settings_project_level_id_0ca1dab1_fk_dictionar FOREIGN KEY (project_level_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: certificate_settings certificate_settings_updated_by_id_2d83e676_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.certificate_settings
    ADD CONSTRAINT certificate_settings_updated_by_id_2d83e676_fk_users_id FOREIGN KEY (updated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: dictionary_items dictionary_items_dict_type_id_08d3c96f_fk_dictionary_types_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dictionary_items
    ADD CONSTRAINT dictionary_items_dict_type_id_08d3c96f_fk_dictionary_types_id FOREIGN KEY (dict_type_id) REFERENCES public.dictionary_types(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expert_groups expert_groups_created_by_id_ea191c03_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups
    ADD CONSTRAINT expert_groups_created_by_id_ea191c03_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expert_groups_members expert_groups_member_expertgroup_id_c0b06855_fk_expert_gr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups_members
    ADD CONSTRAINT expert_groups_member_expertgroup_id_c0b06855_fk_expert_gr FOREIGN KEY (expertgroup_id) REFERENCES public.expert_groups(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: expert_groups_members expert_groups_members_user_id_94d717a7_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expert_groups_members
    ADD CONSTRAINT expert_groups_members_user_id_94d717a7_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_recipient_id_e1133bac_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_recipient_id_e1133bac_fk_users_id FOREIGN KEY (recipient_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_related_project_id_937ebb75_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_related_project_id_937ebb75_fk_projects_id FOREIGN KEY (related_project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_achievements project_achievements_achievement_type_id_1d76d968_fk_dictionar; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_achievements
    ADD CONSTRAINT project_achievements_achievement_type_id_1d76d968_fk_dictionar FOREIGN KEY (achievement_type_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_achievements project_achievements_project_id_99c3182e_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_achievements
    ADD CONSTRAINT project_achievements_project_id_99c3182e_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_advisors project_advisors_project_id_d2ef5924_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_advisors
    ADD CONSTRAINT project_advisors_project_id_d2ef5924_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_advisors project_advisors_user_id_e397bc74_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_advisors
    ADD CONSTRAINT project_advisors_user_id_e397bc74_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_archives project_archives_project_id_9f133d5b_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_archives
    ADD CONSTRAINT project_archives_project_id_9f133d5b_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_change_requests project_change_requests_created_by_id_58f7c62d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_requests
    ADD CONSTRAINT project_change_requests_created_by_id_58f7c62d_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_change_requests project_change_requests_project_id_3231f0af_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_requests
    ADD CONSTRAINT project_change_requests_project_id_3231f0af_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_change_reviews project_change_revie_change_request_id_7de00e2e_fk_project_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_reviews
    ADD CONSTRAINT project_change_revie_change_request_id_7de00e2e_fk_project_c FOREIGN KEY (change_request_id) REFERENCES public.project_change_requests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_change_reviews project_change_revie_workflow_node_id_5aa47440_fk_workflow_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_reviews
    ADD CONSTRAINT project_change_revie_workflow_node_id_5aa47440_fk_workflow_ FOREIGN KEY (workflow_node_id) REFERENCES public.workflow_nodes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_change_reviews project_change_reviews_reviewer_id_3abd4640_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_change_reviews
    ADD CONSTRAINT project_change_reviews_reviewer_id_3abd4640_fk_users_id FOREIGN KEY (reviewer_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditure_reviews project_expenditure__expenditure_id_d8259029_fk_project_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditure_reviews
    ADD CONSTRAINT project_expenditure__expenditure_id_d8259029_fk_project_e FOREIGN KEY (expenditure_id) REFERENCES public.project_expenditures(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditure_reviews project_expenditure__workflow_node_id_d352905a_fk_workflow_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditure_reviews
    ADD CONSTRAINT project_expenditure__workflow_node_id_d352905a_fk_workflow_ FOREIGN KEY (workflow_node_id) REFERENCES public.workflow_nodes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditure_reviews project_expenditure_reviews_reviewer_id_954d0e0c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditure_reviews
    ADD CONSTRAINT project_expenditure_reviews_reviewer_id_954d0e0c_fk_users_id FOREIGN KEY (reviewer_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditures project_expenditures_created_by_id_283ff779_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditures
    ADD CONSTRAINT project_expenditures_created_by_id_283ff779_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditures project_expenditures_leader_reviewed_by_id_3359cdab_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditures
    ADD CONSTRAINT project_expenditures_leader_reviewed_by_id_3359cdab_fk_users_id FOREIGN KEY (leader_reviewed_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditures project_expenditures_project_id_6c79dd16_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditures
    ADD CONSTRAINT project_expenditures_project_id_6c79dd16_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_expenditures project_expenditures_reviewed_by_id_4a719410_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_expenditures
    ADD CONSTRAINT project_expenditures_reviewed_by_id_4a719410_fk_users_id FOREIGN KEY (reviewed_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_members project_members_project_id_bf2e42ec_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_project_id_bf2e42ec_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_members project_members_user_id_2e9d44b1_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_user_id_2e9d44b1_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_phase_instances project_phase_instances_created_by_id_7783b14c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_phase_instances
    ADD CONSTRAINT project_phase_instances_created_by_id_7783b14c_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: project_phase_instances project_phase_instances_project_id_9f3b1467_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.project_phase_instances
    ADD CONSTRAINT project_phase_instances_project_id_9f3b1467_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_batch_id_67b3e4b1_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_batch_id_67b3e4b1_fk FOREIGN KEY (batch_id) REFERENCES public.project_batches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_category_id_2110ba9e_fk_dictionary_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_category_id_2110ba9e_fk_dictionary_items_id FOREIGN KEY (category_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_leader_id_aabb0912_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_leader_id_aabb0912_fk_users_id FOREIGN KEY (leader_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_level_id_8a6f1c0b_fk_dictionary_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_level_id_8a6f1c0b_fk_dictionary_items_id FOREIGN KEY (level_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects projects_source_id_4682911e_fk_dictionary_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_source_id_4682911e_fk_dictionary_items_id FOREIGN KEY (source_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews reviews_phase_instance_id_76b853a5_fk_project_p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_phase_instance_id_76b853a5_fk_project_p FOREIGN KEY (phase_instance_id) REFERENCES public.project_phase_instances(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews reviews_project_id_1ffdb6d1_fk_projects_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_project_id_1ffdb6d1_fk_projects_id FOREIGN KEY (project_id) REFERENCES public.projects(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews reviews_reviewer_id_dbb954a8_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_reviewer_id_dbb954a8_fk_users_id FOREIGN KEY (reviewer_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reviews reviews_workflow_node_id_ac4266fc_fk_workflow_nodes_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_workflow_node_id_ac4266fc_fk_workflow_nodes_id FOREIGN KEY (workflow_node_id) REFERENCES public.workflow_nodes(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: system_settings system_settings_batch_id_09927f7b_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_batch_id_09927f7b_fk FOREIGN KEY (batch_id) REFERENCES public.project_batches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: system_settings system_settings_updated_by_id_cf1dfbba_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_updated_by_id_cf1dfbba_fk_users_id FOREIGN KEY (updated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_expert_assigned_by_id_174c6b8c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_expert_assigned_by_id_174c6b8c_fk_users_id FOREIGN KEY (expert_assigned_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_managed_scope_value_id_b94b760f_fk_dictionary_items_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_managed_scope_value_id_b94b760f_fk_dictionary_items_id FOREIGN KEY (managed_scope_value_id) REFERENCES public.dictionary_items(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_role_fk_id_59b0f6c3_fk_roles_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_role_fk_id_59b0f6c3_fk_roles_id FOREIGN KEY (role_fk_id) REFERENCES public.roles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workflow_configs workflow_configs_batch_id_537df69a_fk_project_batches_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_configs
    ADD CONSTRAINT workflow_configs_batch_id_537df69a_fk_project_batches_id FOREIGN KEY (batch_id) REFERENCES public.project_batches(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workflow_configs workflow_configs_created_by_id_9ce1a151_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_configs
    ADD CONSTRAINT workflow_configs_created_by_id_9ce1a151_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workflow_configs workflow_configs_updated_by_id_92af6584_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_configs
    ADD CONSTRAINT workflow_configs_updated_by_id_92af6584_fk_users_id FOREIGN KEY (updated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workflow_nodes workflow_nodes_role_fk_id_505d424b_fk_roles_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_nodes
    ADD CONSTRAINT workflow_nodes_role_fk_id_505d424b_fk_roles_id FOREIGN KEY (role_fk_id) REFERENCES public.roles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: workflow_nodes workflow_nodes_workflow_id_411643ef_fk_workflow_configs_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_nodes
    ADD CONSTRAINT workflow_nodes_workflow_id_411643ef_fk_workflow_configs_id FOREIGN KEY (workflow_id) REFERENCES public.workflow_configs(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 5g9r8DaLlg8JpXHZKnSbcfPi92T7OvX0dhVr7lMHNAkP4rzKq6eKMuNvXtPpRRt

