# Generated by Django 6.0 on 2025-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', '学生'), ('LEVEL2_ADMIN', '二级管理员'), ('LEVEL1_ADMIN', '一级管理员'), ('TEACHER', '指导教师')], default='STUDENT', max_length=20, verbose_name='角色'),
        ),
    ]
