# Generated by Django 6.0 on 2025-12-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_title_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', '学生'), ('LEVEL2_ADMIN', '二级管理员'), ('LEVEL1_ADMIN', '一级管理员'), ('TEACHER', '指导教师'), ('EXPERT', '评审专家')], default='STUDENT', max_length=20, verbose_name='角色'),
        ),
    ]
