# Generated by Django 6.0 on 2026-01-13 09:07

import django.db.models.deletion
from django.db import migrations, models


def create_default_permissions(apps, schema_editor):
    """创建默认权限"""
    Permission = apps.get_model("users", "Permission")

    permissions = [
        # 用户管理权限
        {
            "code": "manage_students",
            "name": "管理学生",
            "category": "用户管理",
            "description": "查看、创建、编辑、删除学生用户",
        },
        {
            "code": "manage_teachers",
            "name": "管理教师",
            "category": "用户管理",
            "description": "查看、创建、编辑、删除教师用户",
        },
        {
            "code": "manage_experts",
            "name": "管理专家",
            "category": "用户管理",
            "description": "查看、创建、编辑、删除专家用户",
        },
        {
            "code": "manage_level2_admins",
            "name": "管理二级管理员",
            "category": "用户管理",
            "description": "查看、创建、编辑、删除二级管理员",
        },
        {
            "code": "manage_level1_admins",
            "name": "管理一级管理员",
            "category": "用户管理",
            "description": "查看、创建、编辑、删除一级管理员",
        },
        {
            "code": "view_all_users",
            "name": "查看所有用户",
            "category": "用户管理",
            "description": "查看系统中所有用户信息",
        },
        # 项目管理权限
        {
            "code": "manage_own_projects",
            "name": "管理自己的项目",
            "category": "项目管理",
            "description": "创建、编辑、删除自己的项目",
        },
        {
            "code": "view_college_projects",
            "name": "查看本学院项目",
            "category": "项目管理",
            "description": "查看本学院的所有项目",
        },
        {
            "code": "manage_college_projects",
            "name": "管理本学院项目",
            "category": "项目管理",
            "description": "管理本学院的所有项目",
        },
        {
            "code": "view_all_projects",
            "name": "查看所有项目",
            "category": "项目管理",
            "description": "查看系统中所有项目",
        },
        {
            "code": "manage_all_projects",
            "name": "管理所有项目",
            "category": "项目管理",
            "description": "管理系统中所有项目",
        },
        {
            "code": "export_projects",
            "name": "导出项目数据",
            "category": "项目管理",
            "description": "导出项目相关数据",
        },
        # 审核管理权限
        {
            "code": "review_as_teacher",
            "name": "导师审核",
            "category": "审核管理",
            "description": "作为导师审核指导的项目",
        },
        {
            "code": "review_as_college_expert",
            "name": "院级专家评审",
            "category": "审核管理",
            "description": "作为院级专家评审项目",
        },
        {
            "code": "review_as_school_expert",
            "name": "校级专家评审",
            "category": "审核管理",
            "description": "作为校级专家评审项目",
        },
        {
            "code": "manage_college_reviews",
            "name": "管理本学院审核",
            "category": "审核管理",
            "description": "管理本学院的审核流程",
        },
        {
            "code": "manage_all_reviews",
            "name": "管理所有审核",
            "category": "审核管理",
            "description": "管理系统中所有审核流程",
        },
        {
            "code": "assign_reviewers",
            "name": "分配评审人",
            "category": "审核管理",
            "description": "为项目分配评审专家",
        },
        # 批次管理权限
        {
            "code": "manage_batches",
            "name": "管理批次",
            "category": "批次管理",
            "description": "创建、编辑、删除项目批次",
        },
        {
            "code": "view_batches",
            "name": "查看批次",
            "category": "批次管理",
            "description": "查看项目批次信息",
        },
        # 系统配置权限
        {
            "code": "manage_roles",
            "name": "管理角色",
            "category": "系统配置",
            "description": "创建、编辑、删除角色及配置权限",
        },
        {
            "code": "manage_workflows",
            "name": "管理工作流",
            "category": "系统配置",
            "description": "配置审核工作流程",
        },
        {
            "code": "manage_dictionaries",
            "name": "管理数据字典",
            "category": "系统配置",
            "description": "管理系统数据字典",
        },
        {
            "code": "manage_system_settings",
            "name": "管理系统设置",
            "category": "系统配置",
            "description": "配置系统参数和设置",
        },
        {
            "code": "view_system_logs",
            "name": "查看系统日志",
            "category": "系统配置",
            "description": "查看系统操作日志",
        },
        # 通知管理权限
        {
            "code": "send_notifications",
            "name": "发送通知",
            "category": "通知管理",
            "description": "发送系统通知",
        },
        {
            "code": "manage_notifications",
            "name": "管理通知",
            "category": "通知管理",
            "description": "管理系统通知",
        },
    ]

    for perm_data in permissions:
        Permission.objects.create(**perm_data)


def create_default_roles(apps, schema_editor):
    """创建5个默认角色并分配权限"""
    Role = apps.get_model("users", "Role")
    Permission = apps.get_model("users", "Permission")

    # 1. 学生角色
    student_role = Role.objects.create(
        code="STUDENT",
        name="学生",
        description="学生用户，可以创建和管理自己的项目",
        is_system=True,
        is_active=True,
        default_route="/",
        sort_order=1,
    )
    student_permissions = Permission.objects.filter(
        code__in=[
            "manage_own_projects",
        ]
    )
    student_role.permissions.set(student_permissions)

    # 2. 指导教师角色
    teacher_role = Role.objects.create(
        code="TEACHER",
        name="指导教师",
        description="指导教师，可以审核指导的项目",
        is_system=True,
        is_active=True,
        default_route="/teacher/dashboard",
        sort_order=2,
    )
    teacher_permissions = Permission.objects.filter(
        code__in=[
            "review_as_teacher",
            "view_college_projects",
        ]
    )
    teacher_role.permissions.set(teacher_permissions)

    # 3. 评审专家角色
    expert_role = Role.objects.create(
        code="EXPERT",
        name="评审专家",
        description="评审专家，参与项目评审",
        is_system=True,
        is_active=True,
        default_route="/expert/reviews",
        sort_order=3,
    )
    expert_permissions = Permission.objects.filter(
        code__in=[
            "review_as_college_expert",
            "review_as_school_expert",
        ]
    )
    expert_role.permissions.set(expert_permissions)

    # 4. 二级管理员（学院级）
    level2_role = Role.objects.create(
        code="LEVEL2_ADMIN",
        name="二级管理员",
        description="学院级管理员，管理本学院的用户、项目和审核",
        is_system=True,
        is_active=True,
        default_route="/level2-admin/projects",
        sort_order=4,
    )
    level2_permissions = Permission.objects.filter(
        code__in=[
            "manage_students",
            "manage_teachers",
            "manage_experts",
            "view_college_projects",
            "manage_college_projects",
            "manage_college_reviews",
            "assign_reviewers",
            "view_batches",
            "export_projects",
            "send_notifications",
        ]
    )
    level2_role.permissions.set(level2_permissions)

    # 5. 一级管理员（校级）
    level1_role = Role.objects.create(
        code="LEVEL1_ADMIN",
        name="一级管理员",
        description="校级管理员，拥有系统所有权限",
        is_system=True,
        is_active=True,
        default_route="/level1-admin/users/students",
        sort_order=5,
    )
    # 一级管理员拥有所有权限
    level1_role.permissions.set(Permission.objects.all())


def migrate_user_roles(apps, schema_editor):
    """迁移用户的角色数据：将字符串角色转换为外键关联"""
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")

    # 获取所有角色对象
    roles_dict = {role.code: role for role in Role.objects.all()}

    # 更新所有用户
    for user in User.objects.all():
        # role 字段现在是字符串，根据它找到对应的 Role 对象
        if user.role and user.role in roles_dict:
            user.role_fk = roles_dict[user.role]
            user.save(update_fields=["role_fk"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_expert_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="如：manage_users, review_projects",
                        max_length=50,
                        unique=True,
                        verbose_name="权限代码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="权限名称")),
                ("description", models.TextField(blank=True, verbose_name="权限描述")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="如：用户管理、项目管理、审核管理",
                        max_length=50,
                        verbose_name="权限分类",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table": "permissions",
                "ordering": ["category", "code"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "学生"),
                    ("LEVEL2_ADMIN", "二级管理员"),
                    ("LEVEL1_ADMIN", "一级管理员"),
                    ("TEACHER", "指导教师"),
                    ("EXPERT", "评审专家"),
                ],
                default="STUDENT",
                max_length=20,
                verbose_name="角色（旧）",
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="如：STUDENT, TEACHER, LEVEL1_ADMIN",
                        max_length=50,
                        unique=True,
                        verbose_name="角色代码",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="角色名称")),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="系统内置角色不可删除",
                        verbose_name="是否系统内置",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "default_route",
                    models.CharField(
                        blank=True,
                        help_text="登录后默认跳转的路由",
                        max_length=200,
                        verbose_name="默认路由",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="users.permission",
                        verbose_name="权限列表",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "roles",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="users.role",
                verbose_name="角色",
            ),
        ),
        # 初始化权限数据
        migrations.RunPython(create_default_permissions, migrations.RunPython.noop),
        # 初始化角色数据并分配权限
        migrations.RunPython(create_default_roles, migrations.RunPython.noop),
        # 迁移现有用户的角色数据
        migrations.RunPython(migrate_user_roles, migrations.RunPython.noop),
    ]
