# Generated by Django 6.0 on 2026-01-13 10:30

from django.db import migrations


def backfill_role_fk(apps, schema_editor):
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")

    roles_by_code = {role.code: role for role in Role.objects.all()}
    default_role = roles_by_code.get("STUDENT")

    for user in User.objects.filter(role_fk__isnull=True):
        role_code = getattr(user, "role", None)
        role_obj = roles_by_code.get(role_code) or default_role
        if role_obj:
            user.role_fk = role_obj
            user.save(update_fields=["role_fk"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_add_role_permission_tables"),
    ]

    operations = [
        migrations.RunPython(backfill_role_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
