# Generated by Django 6.0 on 2026-01-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_seed_project_level_items'),
        ('users', '0006_backfill_role_fk_and_drop_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='scope_dimension',
            field=models.CharField(blank=True, choices=[('COLLEGE', '学院'), ('PROJECT_CATEGORY', '项目类别'), ('PROJECT_LEVEL', '项目级别'), ('KEY_FIELD', '重点领域')], help_text='管理员角色的数据范围维度。非管理员角色留空。', max_length=50, null=True, verbose_name='数据范围维度'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_scope_value',
            field=models.ForeignKey(blank=True, help_text='管理员用户负责的维度值（如学院、项目类别等）。对应角色的 scope_dimension。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by_users', to='dictionaries.dictionaryitem', verbose_name='管理范围值'),
        ),
    ]
