# Generated by Django 6.0 on 2026-01-14 10:27

from django.db import migrations


def migrate_expert_users_to_teacher(apps, schema_editor):
    """
    将 EXPERT 角色的用户迁移为 TEACHER 角色
    """
    Role = apps.get_model("users", "Role")
    User = apps.get_model("users", "User")

    # 获取 EXPERT 和 TEACHER 角色
    try:
        expert_role = Role.objects.get(code="EXPERT")
    except Role.DoesNotExist:
        # 如果没有 EXPERT 角色，跳过迁移
        return

    try:
        teacher_role = Role.objects.get(code="TEACHER")
    except Role.DoesNotExist:
        # 如果没有 TEACHER 角色，创建一个
        teacher_role = Role.objects.create(
            code="TEACHER", name="指导教师", is_system=True, is_active=True
        )

    # 将所有 EXPERT 用户改为 TEACHER
    expert_users_count = User.objects.filter(role_fk=expert_role).update(
        role_fk=teacher_role
    )

    if expert_users_count > 0:
        print(f"已将 {expert_users_count} 个 EXPERT 用户迁移为 TEACHER 角色")

    # 删除 EXPERT 角色（如果不是系统内置）
    if not expert_role.is_system:
        expert_role.delete()
        print("已删除 EXPERT 角色")


def reverse_migration(apps, schema_editor):
    """
    回滚操作：将 TEACHER 改回 EXPERT（如需要）
    """
    # 这里不做实际操作，因为无法确定哪些是从 EXPERT 迁移来的
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_role_scope_dimension_user_managed_scope_value"),
        ("dictionaries", "__latest__"),  # 确保字典表已创建
    ]

    operations = [
        migrations.RunPython(migrate_expert_users_to_teacher, reverse_migration),
    ]
