# Generated by Django 6.0 on 2026-01-14 10:27

from django.db import migrations


def populate_admin_scope_values(apps, schema_editor):
    """
    为学院管理员填充 managed_scope_value
    如果角色的 scope_dimension 是 COLLEGE，则根据用户的 college 字段查找对应的字典项
    """
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")
    DictionaryItem = apps.get_model("dictionaries", "DictionaryItem")
    DictionaryType = apps.get_model("dictionaries", "DictionaryType")

    # 获取学院字典类型
    try:
        college_dict_type = DictionaryType.objects.get(code="college")
    except DictionaryType.DoesNotExist:
        print("警告：未找到学院字典类型，跳过管理员范围值填充")
        return

    # 查找所有 scope_dimension 为 COLLEGE 的角色
    college_roles = Role.objects.filter(scope_dimension="COLLEGE")

    updated_count = 0
    for role in college_roles:
        # 查找该角色的所有用户
        users = User.objects.filter(role_fk=role, college__isnull=False)

        for user in users:
            if not user.college:
                continue

            # 查找对应的学院字典项
            try:
                college_item = DictionaryItem.objects.get(
                    dict_type=college_dict_type, value=user.college
                )
                user.managed_scope_value = college_item
                user.save(update_fields=["managed_scope_value"])
                updated_count += 1
            except DictionaryItem.DoesNotExist:
                print(
                    f"警告：用户 {user.real_name}({user.employee_id}) 的学院 '{user.college}' 在字典中不存在"
                )
                continue

    if updated_count > 0:
        print(f"已为 {updated_count} 个学院管理员填充管理范围值")


def reverse_migration(apps, schema_editor):
    """
    回滚操作：清空 managed_scope_value
    """
    User = apps.get_model("users", "User")
    User.objects.all().update(managed_scope_value=None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_migrate_expert_to_teacher"),
        ("dictionaries", "__latest__"),
    ]

    operations = [
        migrations.RunPython(populate_admin_scope_values, reverse_migration),
    ]
