# Generated by Django 6.0 on 2026-01-14 11:08

from django.db import migrations


def fix_system_roles(apps, schema_editor):
    """
    修正系统角色：
    1. 只有 STUDENT、TEACHER、LEVEL1_ADMIN 三个角色是系统内置(is_system=True)
    2. 更新 TEACHER 角色名称从"指导教师"改为"教师"
    3. 更新 LEVEL1_ADMIN 角色名称为"校级管理员"
    """
    Role = apps.get_model("users", "Role")

    # 定义系统内置角色
    system_roles = ["STUDENT", "TEACHER", "LEVEL1_ADMIN"]

    # 设置系统角色
    Role.objects.filter(code__in=system_roles).update(is_system=True)

    # 非系统角色设置为 is_system=False
    Role.objects.exclude(code__in=system_roles).update(is_system=False)

    # 更新角色名称
    teacher_role = Role.objects.filter(code="TEACHER").first()
    if teacher_role:
        teacher_role.name = "教师"
        teacher_role.save()

    level1_admin_role = Role.objects.filter(code="LEVEL1_ADMIN").first()
    if level1_admin_role:
        level1_admin_role.name = "校级管理员"
        level1_admin_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_populate_admin_scope_values"),
    ]

    operations = [
        migrations.RunPython(fix_system_roles, migrations.RunPython.noop),
    ]
