# Generated by Django 6.0 on 2026-01-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fix_system_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
