# Generated by Django 6.0 on 2026-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
