# Generated by Django 6.0 on 2026-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='scope_dimension',
            field=models.CharField(blank=True, choices=[('COLLEGE', '学院'), ('PROJECT_CATEGORY', '项目类别'), ('PROJECT_LEVEL', '项目级别'), ('PROJECT_SOURCE', '项目来源'), ('KEY_FIELD', '重点领域代码')], help_text='管理员角色的数据范围维度。非管理员角色留空。', max_length=50, null=True, verbose_name='数据范围维度'),
        ),
    ]
