# Generated by Django 6.0 on 2026-01-15 10:30

from django.conf import settings
from django.db import migrations, models


def populate_is_expert(apps, schema_editor):
    User = apps.get_model("users", "User")
    Role = apps.get_model("users", "Role")
    ExpertGroup = apps.get_model("reviews", "ExpertGroup")

    expert_role = Role.objects.filter(code="EXPERT").first()
    if expert_role:
        User.objects.filter(role_fk=expert_role).update(is_expert=True)

    through = ExpertGroup.members.through
    member_ids = through.objects.values_list("user_id", flat=True).distinct()
    if member_ids:
        User.objects.filter(id__in=member_ids).update(is_expert=True)


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0012_alter_expertgroup_members"),
        ("users", "0013_alter_role_scope_dimension"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_expert",
            field=models.BooleanField(default=False, verbose_name="是否专家"),
        ),
        migrations.AddField(
            model_name="user",
            name="expert_assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="assigned_experts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="专家设置人",
            ),
        ),
        migrations.RunPython(populate_is_expert, reverse_code=migrations.RunPython.noop),
    ]
