# Generated by Django 6.0 on 2026-01-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_login_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
