# Generated by Django 6.0 on 2026-01-16 01:52

from django.db import migrations


def unify_level2_admin_roles(apps, schema_editor):
    """
    统一所有有scope_dimension的角色：
    1. 确保所有有scope_dimension的角色default_route都指向二级管理员页面
    2. 这样所有非系统预定义角色（由校级管理员创建的）都是二级管理员
    """
    Role = apps.get_model("users", "Role")

    # 更新所有有scope_dimension的角色，确保default_route正确
    roles_to_update = Role.objects.filter(scope_dimension__isnull=False)

    for role in roles_to_update:
        # 统一设置为二级管理员的默认路由
        if not role.default_route or role.default_route == "/level2-admin/statistics":
            role.default_route = "/level2-admin/projects"
            role.save(update_fields=["default_route"])

    print(f"已更新 {roles_to_update.count()} 个二级管理员角色的默认路由")


def reverse_unify(apps, schema_editor):
    """回滚操作（可选）"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_permissions_system"),
    ]

    operations = [
        migrations.RunPython(unify_level2_admin_roles, reverse_unify),
    ]
