# Generated by Django 6.0 on 2026-01-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_unify_level2_admin_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expert_scope',
            field=models.CharField(blank=True, choices=[('SCHOOL', '一级专家组'), ('COLLEGE', '二级专家组')], default='COLLEGE', max_length=20, verbose_name='专家级别'),
        ),
    ]
