# Generated by Django 6.0 on 2025-12-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='字典类型编码')),
                ('name', models.CharField(max_length=100, verbose_name='字典类型名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置字典类型不可删除', verbose_name='系统内置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'db_table': 'dictionary_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=50, verbose_name='选项值')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('extra_data', models.JSONField(blank=True, help_text='JSON格式的额外配置', null=True, verbose_name='扩展数据')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dictionaries.dictionarytype', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典条目',
                'verbose_name_plural': '字典条目',
                'db_table': 'dictionary_items',
                'ordering': ['dict_type', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['dict_type', 'is_active'], name='dictionary__dict_ty_efa91e_idx')],
                'unique_together': {('dict_type', 'value')},
            },
        ),
    ]
