# Generated by Django 6.0 on 2025-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_seed_initial_dictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryitem',
            name='template_file',
            field=models.FileField(blank=True, help_text='关联的模板文件（如申请书模板）', null=True, upload_to='dictionary_templates/', verbose_name='模板文件'),
        ),
    ]
