# Generated by Django 6.0 on 2025-12-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('APPLICATION', '申报审核'), ('CLOSURE', '结题审核')], max_length=20, verbose_name='审核类型')),
                ('review_level', models.CharField(choices=[('LEVEL2', '二级审核'), ('LEVEL1', '一级审核')], max_length=20, verbose_name='审核级别')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '审核通过'), ('REJECTED', '审核不通过')], default='PENDING', max_length=20, verbose_name='审核状态')),
                ('comments', models.TextField(blank=True, verbose_name='审核意见')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('closure_rating', models.CharField(blank=True, choices=[('EXCELLENT', '优秀'), ('GOOD', '良好'), ('QUALIFIED', '合格'), ('UNQUALIFIED', '不合格'), ('DEFERRED', '延期')], max_length=20, null=True, verbose_name='结题评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
