# Generated by Django 6.0 on 2025-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('APPLICATION', '申报审核'), ('MID_TERM', '中期审核'), ('CLOSURE', '结题审核')], max_length=20, verbose_name='审核类型'),
        ),
    ]
