# Generated by Django 6.0 on 2025-12-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_review_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专家组名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expert_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('members', models.ManyToManyField(limit_choices_to={'role': 'EXPERT'}, related_name='expert_groups', to=settings.AUTH_USER_MODEL, verbose_name='专家成员')),
            ],
            options={
                'verbose_name': '专家组',
                'verbose_name_plural': '专家组',
                'db_table': 'expert_groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
