# Generated by Django 6.0 on 2025-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_expertgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertgroup',
            name='scope',
            field=models.CharField(default='COLLEGE', max_length=20, verbose_name='专家组级别'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_level',
            field=models.CharField(choices=[('TEACHER', '导师审核'), ('LEVEL2', '二级审核'), ('LEVEL1', '一级审核')], max_length=20, verbose_name='审核级别'),
        ),
    ]
