# Generated by Django 6.0 on 2026-01-13 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_review_review_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_template',
        ),
        migrations.AlterField(
            model_name='expertgroup',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'role_fk__code': 'EXPERT'}, related_name='expert_groups', to=settings.AUTH_USER_MODEL, verbose_name='专家成员'),
        ),
    ]
