# Generated by Django 6.0 on 2026-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_remove_review_review_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_level',
            field=models.CharField(help_text='动态值，由工作流节点配置决定', max_length=50, verbose_name='审核级别/角色'),
        ),
    ]
