# Generated by Django 6.0 on 2026-02-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0012_remove_workflownode_review_template_and_more'),
        ('reviews', '0010_alter_review_review_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='workflow_node',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviews',
                to='system_settings.workflownode',
                verbose_name='关联工作流节点',
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='is_expert_review',
            field=models.BooleanField(default=False, verbose_name='是否专家评审任务'),
        ),
    ]
