# Generated by Django 6.0 on 2026-01-14 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_workflow_node_and_expert_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertgroup',
            name='members',
            field=models.ManyToManyField(limit_choices_to={'role_fk__code': 'TEACHER'}, related_name='expert_groups', to=settings.AUTH_USER_MODEL, verbose_name='专家成员'),
        ),
    ]
