# Generated by Django 6.0 on 2026-03-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0012_alter_expertgroup_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("APPLICATION", "申报审核"),
                    ("MID_TERM", "中期审核"),
                    ("CLOSURE", "结题审核"),
                ],
                max_length=20,
                verbose_name="审核类型",
            ),
        ),
    ]
