# Generated by Codex on 2026-01-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_alter_review_review_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_project_1fd85d_idx",
        ),
        migrations.RemoveField(
            model_name="review",
            name="review_level",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["project", "workflow_node"],
                name="reviews_proj_wfnode_idx",
            ),
        ),
    ]
